### ISSUE TITLE
Release TODOs

### ISSUE THREAD

**Issue by danomatika** [oribotic/oribotic-instruments#4]
_This is a running "Work In Progress" issue meant for discussion and review. Please do not close until all are agreed._

For lack of a better place right now, I'm putting these TODOs here. My overall running work is in my [develop branch](https://github.com/danomatika/oribotic-instruments/tree/develop) but I will periodically open PRs when I finish a certain set of work to merge changes back here.

Puredata:
* [x] changes and basic info for Pd vanilla desktop usage
* [x] add basic `oi` abstraction library
* [x] update existing templates to remove osc lib dependency
* ~~update existing templates to use `oi` library?~~
* [x] ~~add s12 and k48 abstractions (should be easy, but I have no way to test)~~ have generic instrument abs

Firmware:
* [x] (any) required changes for use with Pd vanilla
* [x] add receiving arg range checking (mostly there, need to double check)
* ~~MIDI: add ability to query notes ala OSC `/getNotes`~~
* ~~OSC: add ability to set MPR A-D status (MIDI has this but is this needed?)~~

PdParty:
* [x] add mobile template / test for PdParty (iPad)

General repo info:
* [x] introduce readme and changelog template
* [x] double-check source code attribution & add headers where necessary
* [x] add message spec html or (to) readme

To try out my develop branch, you can either add my fork as a remote and checkout the branch *or* make a separate clone of my fork directly: https://stackoverflow.com/questions/9153598/how-do-i-fetch-a-branch-on-someone-elses-fork-on-github

**Comment by danomatika** [comment]
Current high-level abstractions:

![oi allcontrols](https://github.com/oribotic/oribotic-instruments/assets/480637/4212dd59-f5d1-440d-87bc-e70de47653f0)
![oi o y8](https://github.com/oribotic/oribotic-instruments/assets/480637/6bc36137-bbe0-4dce-898c-fa4cf65d0130)
![oi m y8](https://github.com/oribotic/oribotic-instruments/assets/480637/273ffa27-a309-40b3-a18e-8c7f07bda420)

I made `oi.allcontrols` to avoid having to duplicate the control message info in each of the help patches.

**Comment by danomatika** [comment]
I realized there is no need for instrument-specific wrappers and that we can use the same abstraction with the number of panels as a creation argument. We could probably come up with a better name, it's `oi.*.instrument` for now.

<img width="554" alt="Screenshot 2023-08-20 at 11 23 47 PM" src="https://github.com/oribotic/oribotic-instruments/assets/480637/7887e47c-1c36-4771-93ae-3b72461c6de4">

**Comment by oribotic** [comment]
![play](https://github.com/oribotic/oribotic-instruments/assets/6670535/faa73f08-9ff8-4ad9-89b9-28b9f485bd1a)
![tune](https://github.com/oribotic/oribotic-instruments/assets/6670535/a18c1367-d7e4-4264-acda-fd23dedf6a06)

Adding to this list of todos, just for the exhibition screen design

So this is the preliminary screen design I'm working on, possibly a third coming with a graph display. It would be handy to have an abstraction that allows for display of individual panel data. 

[ ] oi.panel [0-47] abstraction for displaying and/or composing with panels, instantiated by ol.panel [#panel]

**Comment by danomatika** [comment]
Ok, all tasks should be done now. I've demoted the extra firmware stuff and finished the PdParty scenes in #9.

**Comment by danomatika** [comment]
Closing after latest merge.

**Comment by danomatika** [comment]
Note: I still suggest tagging the releases.
